### ISSUE TITLE
Feature Request: Version command

### ISSUE THREAD

**Issue by tedav** [henrikolsson/demogorgon#1]
I would like to request added functionality for checking the current version number and build of the game running on the server (the same information as Shift+v on the current UnNethack public server [us.un.nethack.nu])

Example Implementation:

[demogorgon]: Unix UnNetHack Version 5.3.0 - last build Tue Sept 30 19:31:30 2014.
[johnny_random_user](!version): Wow! That was amazingly convenient and helpful! I should donate everything I own to this game!
[other_random_user_lets_call_him_Fred]: Me too! This is my new favorite thing!

**Comment by henrikolsson** [comment]
Took a while, but done:
&lt;user> .version
&lt;demogorgon> Unix UnNetHack Version 5.3.1 - last build Sat May 30 14:25:43 2015.

**Comment by tedav** [comment]
Thanks! I really appreciate you doing this.
